# -*- coding: utf-8 -*-
"""
Created on Mon Jun 23 10:26:15 2014

@author: Brian
"""

#Identification
CUSIP = 'ID_CUSIP'
NAME = 'NAME'
SECTOR = 'MARKET_SECTOR_DES'
TICKER = 'TICKER'
PARSE_KEY = 'PARSEKEYABLE_DES'

#General
PX_A = 'PX_ASK'
PX_M = 'PX_MID'
PX_B = 'PX_BID'
PX_L = 'PX_LAST'
YLD_C_A = 'YLD_CNV_ASK'
YLD_C_B = 'YLD_CNV_BID'
YLD_C_M = 'YLD_CNV_MID'

#Mtge Bonds
MTG_CF = 'MTG_CASH_FLOW'
MTG_DYN_CF = 'ALLOW_DYNAMIC_CASHFLOW_CALCS'
MTG_FWD_RT = 'APPLY_FWD_RATE'
MTG_IX_USED = 'MTG_INDEX_USED_SUB_PER_SETTLE'
MTG_PP_MULT = 'MTG_PREPAY_SPEED'
MTG_PP_TYP = 'MTG_PREPAY_TYP'
MTG_PP_VECT = 'PREPAY_VECTOR'

#Closed End Funds
NAV = 'FUND_NET_ASSET_VAL'
DPS_ANNUAL_GROSS = 'EQY_IND_DPS_ANNUAL_GROSS'
DVD_YLD_12M = 'EQY_DVD_YLD_12M'
DVD_YLD_IND = 'EQY_DVD_YLD_IND'
PREMIUM = 'CEF_PCT_PREM'
PX_LAST = 'PX_LAST'
SHORT_INT = 'SHORT_INT'
SHORT_INT_RATIO = 'SHORT_INT_RATIO'
TR_1D_GROSS = 'DAY_TO_DAY_TOT_RETURN_GROSS_DVDS'
TURNOVER = 'TURNOVER'
VOLUME = 'VOLUME'
